### ISSUE TITLE
Scan is not working

### ISSUE THREAD

**Issue by Toxich4** [PhonePe/mantis#4] opened 2023-12-28 12:09 UTC
After installation, I try to scan host but get an error.
Tried it on clean ubuntu 20.04 and 22.04.
The error is below. 

```
🦗 Mantis > mantis onboard -o test -t ginandjuice.shop


              __  __             _   _
             |  \/  | __ _ _ __ | |_(_)___
             | |\/| |/ _` | '_ \| __| / __|
             | |  | | (_| | | | | |_| \__ \
             |_|  |_|\__,_|_| |_|\__|_|___/

                                Recon Automation Framework (v1.0)

[2023-12-28 12:04:31,106] --> INFO: MANTIS ASSET DISCOVERY - STARTED
[2023-12-28 12:04:31,106] --> INFO: Executing workname workflowName='default' schedule='daily between 00:00 and 04:00' cmd=[] scanNewOnly=False workflowConfig=[Module(moduleName='discovery', tools=['Subfinder', 'Amass'], order=1), Module(moduleName='prerecon', tools=['FindCDN', 'Naabu'], order=2), Module(moduleName='activehostscan', tools=['HTTPX_Active', 'HTTPX'], order=3), Module(moduleName='activerecon', tools=['Wafw00f'], order=4), Module(moduleName='scan', tools=['DNSTwister', 'Nuclei', 'Corsy'], order=5), Module(moduleName='secretscanner', tools=['SecretScanner'], order=6)]
[2023-12-28 12:04:31,118] --> INFO: Inserting user input into database
Traceback (most recent call last):
  File "/home/mantis/launch.py", line 29, in <module>
    main()
  File "/home/mantis/launch.py", line 23, in main
    MantisWorkflow.select_workflow(args=args)
  File "/home/mantis/mantis/workflows/mantis_workflow.py", line 9, in select_workflow
    asyncio.run(Workflow.workflow_executor(args))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/mantis/mantis/modules/workflow.py", line 62, in workflow_executor
    await CrudUtils.insert_assets(assets=asset_dict_list, source='internal')
  File "/home/mantis/mantis/utils/crud_utils.py", line 73, in insert_assets
    await add_assets_query(asset_data=asset_list)
  File "/home/mantis/mantis/db/crud_assets.py", line 7, in add_assets_query
    asset = await assets_collection.insert_many(asset_data, False) # 'ordered': "false"}
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 707, in insert_many
    blk.execute(write_concern, session=session)
  File "/usr/local/lib/python3.9/site-packages/pymongo/bulk.py", line 513, in execute
    return self.execute_command(generator, write_concern, session)
  File "/usr/local/lib/python3.9/site-packages/pymongo/bulk.py", line 390, in execute_command
    with client._tmp_session(session) as s:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1729, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1712, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1657, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mantis.db:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 658d644f8a6b880a6e3b7bf4, topology_type: Unknown, servers: [<ServerDescription ('mantis.db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mantis.db:27017: [Errno 111] Connection refused')>]>
```

**Comment by Prateek-Thakare** [comment] 2023-12-28 15:13
Hey @Toxich4 
Are you trying to run Mantis on a laptop with VPN or Netskope client? Generally, this error is related to accessing to MongoDB docker which has been assigned a static IP as 10.10.0.3. Can you please confirm this? Feel free to ping me on discord too. 

Thanks
Prateek

**Comment by Toxich4** [comment] 2023-12-28 18:54
No, I'm using virtual box with bridged adapter network setting

**Comment by 0xbharath** [comment] 2023-12-29 06:23
Can you check the following on your VM:

1. Can you confirm if mongo container is running (`docker ps`) ?
2. Can you check if `mantis.db` is resolving to `10.10.0.3` (`dig mantis.db`) ?
3. Manually connect to MongoDB using a mongo client (`mongosh "mongodb://10.10.0.3:27017/`) ?

**Comment by Toxich4** [comment] 2023-12-30 08:25
Yeah, it looks like mango docker is not starting
**sudo docker ps**
```
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS                             PORTS                                                                            NAMES
fadbf9556bb9   docker-mantis          "tail -F /dev/random"    7 minutes ago   Up 7 minutes                                                                                                        mantis
7b8fe6594d16   appsmith/appsmith-ce   "/opt/appsmith/entry…"   7 minutes ago   Up 17 seconds (health: starting)   0.0.0.0:1337->80/tcp, :::1337->80/tcp, 0.0.0.0:1338->443/tcp, :::1338->443/tcp   appsmith
c0b06da7637f   mongo:latest           "docker-entrypoint.s…"   7 minutes ago   Restarting (132) 49 seconds ago                                                                                     mongodb
```

**dig mantis.db**
```
; <<>> DiG 9.18.12-0ubuntu0.22.04.3-Ubuntu <<>> mantis.db
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13970
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mantis.db.                     IN      A

;; ANSWER SECTION:
mantis.db.              0       IN      A       10.10.0.3

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat Dec 30 08:18:26 UTC 2023
;; MSG SIZE  rcvd: 54
```

**Comment by Toxich4** [comment] 2024-01-08 22:31
Sorry for long answer

There was too much simular warnings

```
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

/usr/local/bin/docker-entrypoint.sh: line 416:    26 Illegal instruction     (core dumped) "${mongodHackedArgs[@]}" --fork
```

I've tried to fix this issue but nothing helped me. Tommorow I'll try to install it on my MacOS

**Comment by Toxich4** [comment] 2024-01-09 19:05
I installed the same ubuntu 22.04 on VB on MacOS and everything works perfectly.
I think it's a problem with VB at Windows 11, like on this forum - https://forums.virtualbox.org/viewtopic.php?t=109776

**Comment by Prateek-Thakare** [comment] 2024-01-12 06:15
Hey
Yes we also got the same error. Downgrading mongo version in docker file might work. 
Closing this as the issue is resolved. Feel free to reopen in case you face any issues. 

Thanks

**Closed by Prateek-Thakare** 2024-01-12 06:15 UTC
Labels: bug
