### ISSUE TITLE
Bug is that same domain can not be part of 2 organisations

### ISSUE THREAD

**Issue by nrudrappa-godaddy** [PhonePe/mantis#19] opened 2024-04-23 08:24 UTC
Create an organization and make sure xyz.com is part of it.

Now onboard another organization with xyz.com being part of it application throws error as "[2024-04-23 08:23:39,456] --> ERROR: No input available for tools. Quitting!!"

can't we create 2 organisation with some domains in common.

**Comment by NaveenRudra** [comment] 2024-04-26 13:22
I still feel we should allow the scanning of a single domain that is already part of an organisation. If the issue is fixed on a domain it does not make sense to scan the complete org.

**Comment by Prateek-Thakare** [comment] 2024-05-30 08:48
Hey @NaveenRudra 
The latest commit adds the feature to scan a single subdomain of an org using `--sub` flag. Please note that there might be some discrepancies in the efficiency part as some of the tools might not run. This is Work in Progress. 

Thanks for suggesting this change. 

Regards,
Prateek

**Closed by Prateek-Thakare** 2024-05-30 08:48 UTC
Labels: bug, enhancement
